version: '3'
services:
    nginx:
        container_name: DIGRAM_NGNIX
        image: 'nginx:latest'
        ports:
            - '80:8080'
        volumes:
            - './var/www:/var/www'
            - './config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './config/nginx/conf.d/:/etc/nginx/conf.d/:ro'
        networks:
            - lempnet
    php:
        container_name: DIGRAM_PHP_FPM
        build: ./config/php-fpm
        ports:
            - '9000'
        volumes:
            - './var/www:/var/www'
            - './config/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro'
        networks:
            - lempnet
    mysqldb:
        container_name: DIGRAM_MYSQL
        image: 'mysql:5.7'
        volumes:
            - './data/mysql:/var/lib/mysql'
        restart: always
        environment:
            - MYSQL_ROOT_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - '${MYSQL_PORT}:3306'
        expose:
            - '${MYSQL_PORT}'    
        networks:
            - lempnet
    phpmyadmin:
        container_name: DIGRAM_PHPMYADMIN
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - PMA_HOST=mysqldb
        depends_on:
            - mysqldb
        networks:
            - lempnet
networks:
    lempnet:
        driver: bridge
