name: Development QC and Unit Testing

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    working-directory: ./var/www/digram

jobs:
  app-checking-testing:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: digram-testing
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Install Dependencies
        run: composer update
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: App config cache
        run: php artisan config:cache
      - name: Generate key
        run: php artisan key:generate
      - name: Create DB and schemas
        run: php artisan migrate:refresh
      - name: Generate DB Seed
        run: php artisan db:seed
      - name: Install phpmd
        run: composer require --dev phpmd/phpmd
      - name: phpMD
        run: vendor/bin/phpmd app/ ansi ruleset-laravel.xml
      - name: php-cs-fixer
        run: php artisan fixer:fix --dry-run
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit

